# Generated by Django 2.0.2 on 2018-02-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policemen',
            fields=[
                ('policeID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('stationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stationName', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Request',
            fields=[
                ('requestID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='policemen',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Stations'),
        ),
    ]
