# Generated by Django 2.0.2 on 2018-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('polls', '0004_auto_20180308_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeentry',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='policeentry',
            old_name='policeID',
            new_name='PoliceID',
        ),
        migrations.RenameField(
            model_name='policeentry',
            old_name='station',
            new_name='Station',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='coordinates',
            new_name='Coordinates',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='data',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='district',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='stationID',
            new_name='StationID',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='stationName',
            new_name='StationName',
        ),
        migrations.RenameField(
            model_name='user_request',
            old_name='data',
            new_name='Details',
        ),
        migrations.RenameField(
            model_name='user_request',
            old_name='requestID',
            new_name='RequestID',
        ),
        migrations.AddField(
            model_name='user_request',
            name='Coordinates',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_request',
            name='RegisteredNo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user_request',
            name='UserName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
