# Generated by Django 2.0.2 on 2018-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_user_request_aadhaarid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='Image',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
